services:
  web:
    build: .
    ports:
      - "0.0.0.0:8000:8000"
      - "[::1]:8000:8000"
    env_file:
      - .env
    volumes:
      - ./src/instance:/app/src/instance
      - ./src/app/data:/app/src/app/data
