"""Add user_id to logs table

Revision ID: add_user_id_to_logs
Revises: eeb11406ea32
Create Date: 2024-02-11 18:30:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_user_id_to_logs'
down_revision = 'eeb11406ea32'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_logs_user_id', 'users', ['user_id'], ['id'])

    # Set existing logs to the first admin user (temporary solution)
    op.execute('UPDATE logs SET user_id = (SELECT id FROM users WHERE is_admin = 1 LIMIT 1)')

    # Make user_id non-nullable after setting default values
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('user_id', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_logs_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
